DmBuddyMvc/Controllers/DemosController.cs
using Microsoft.AspNetCore.Mvc;

namespace DmBuddyMvc.Controllers
{
    public class DemosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DmBuddyMvc/Controllers/PricingController.cs
using DmBuddyMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DmBuddyMvc.Controllers
{
    public class PricingController : Controller
    {
        private readonly AccountServices _accountservices;

        public PricingController(AccountServices accountservices)
        {
            _accountservices = accountservices;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Checkout(int months)
        {
            TempData["PurchaseMessage"] = "Thanks for your purchase! Your account has been upgraded to Premium. You can view your subscription details by clicking on your username.";
            var result = await _accountservices.AddPremiumSubscriptionToUserForMonths(User, months);
            if (result == false)
                return StatusCode(StatusCodes.Status500InternalServerError);

            return Ok();
        }

        public IActionResult Thanks()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }
    }
}

DmBuddyMvc/Views/Shared/_AdSense.cshtml
@using DmBuddyMvc.Helpers;

@if (!User.IsAtLeastPremium())
{
    <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7867641612810953"
                crossorigin="anonymous"></script>
    </head>
}

DmBuddyMvc/Views/Shared/_Layout.cshtml
@using DmBuddyMvc.Helpers;
<!DOCTYPE html>

<link rel="icon" type="image/png" href="~/logo.png" />

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DmBuddy - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DmBuddyMvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="m-2" width="30" height="30" src="~/logo.png"/>DmBuddy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            @if(User.IsAtLeastBasic()){
                                <a class="nav-link text-dark" asp-area="" asp-controller="Encounter" asp-action="SavedEncounters">Encounters</a>
                            }else{
                                <a class="nav-link text-dark" asp-area="" asp-controller="Encounter" asp-action="Index">Encounter</a>
                            }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pricing" asp-action="Index">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demos" asp-action="Index">Demos</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <ul class="list-inline text-center">
                <li class="list-inline-item">
                    &copy; 2023 <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="list-inline-item">
                    <i class="bi bi-envelope-at pe-1"></i><a href="mailto:dmbuddy.service@gmail.com">dmbuddy.service@gmail.com</a>
                </li>
            </ul>
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>